require("dotenv").config();

const multer = require("multer");

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10*1024*1024}
});

const express = require("express");
const cors = require("cors");
const helmet = require("helmet");

const app = express();
const PORT = process.env.PORT || 5000;

const AWS = require("aws-sdk");
const s3 = new AWS.S3({
  region: process.env.AWS_REGION,
  accesskeyId: process.env.AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY
});
const AWS_S3_BUCKET_NAME = process.env.AWS_S3_BUCKET_NAME;

app.use(helmet({
    crossOriginResourcePolicy: { policy: "cross-origin" },
  }));
app.use(cors({
  origin: ['http://localhost:3000', 'http://localhost:5173'], // Add your local port here (React uses 3000 or Vite uses 5173)
  credentials: true
}));
app.use(express.json());

app.get("/api/files", async (req, res, next) => { 
  try { 
    const result = await s3 
      .listObjectsV2({ 
        Bucket: AWS_S3_BUCKET_NAME, 
        Prefix: "uploads/", 
        MaxKeys: 1000 
      }) 
      .promise(); 
    const files = (result.Contents || []).map((file) => ({ 
      key: file.Key, 
      name: file.Key.split("/").pop(), 
      size: file.Size, 
      lastModified: file.LastModified 
    })); 
    res.json({ files });
  } catch (error) { 
    next(error); 
  } 
}); 

app.get("/", (req, res) => {
  res.json({
    message: "Cloud File Manager backend is running",
    status: "ok"
  });
});

app.get("/health", (req, res) => {
  res.json({
    status: "ok",
    timestamp: new Date().toISOString()
  });
});

app.post("/api/files/upload", upload.single("file"), async (req, res, next) => { 
  try { 
    if (!req.file) { 
      return res.status(400).json({ message: "No file was provided." }); 
    } 
    const safeName = req.file.originalname.replace( 
      /[^a-zA-Z0-9._-]/g, 
      "_" 
    );
    const key = `uploads/${Date.now()}-${safeName}`; 
    await s3.upload({ 
      Bucket: BUCKET_NAME, 
      Key: key, 
      Body: req.file.buffer, 
      ContentType: req.file.mimetype 
    }).promise(); 
    res.status(201).json({ 
      message: "File uploaded successfully.", 
      file: { 
        key, 
        name: req.file.originalname, 
        size: req.file.size 
      } 
    }); 
  } catch (error) { 
    next(error); 
  } 
}); 

// filename: backend/server.js | Code Generated by Sidekick is for learning and experimentation purposes only. 

app.use((error, req, res, next) => { 

  console.error(error); 

  res.status(500).json({ 

    message: error.message || "Server error." 

  }); 

}); 

app.listen(PORT, "0.0.0.0", () => {
  console.log(`Server running on port ${PORT}`);
});
